# pipeline_bas_v2.yml
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: ETL Pipeline Base v2
experiment_name: etl_pipeline_experiment

settings:
  default_compute: azureml:clusterai
  default_datastore: azureml:workspaceblobstore

inputs:
  input_datastore:
    type: uri_folder
    path: azureml://datastores/base_data/paths/rawdata

outputs:
  output_datastore:
    type: uri_folder
    path: azureml://datastores/ml_data/paths/platinumdata
    mode: rw_mount

jobs:
  etl_job:
    type: command
    component: file:./src/data/etl.yml
    inputs:
      input_datastore: ${{parent.inputs.input_datastore}}
      ult_periodo: 202511
      n_periodos: "None"
      all_periodos: "True"
      platinum_version: "v1"
    outputs:
      output_datastore: ${{parent.outputs.output_datastore}}
