# pipeline_ml.yml
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: ML Pipeline - Inicial Regular
experiment_name: ml_pipeline_experiment

settings:
  default_compute: azureml:clusterai
  default_datastore: azureml:workspaceblobstore

inputs:
  input_datastore:
    type: uri_folder
    path: azureml://datastores/base_data/paths/rawdata
  ult_periodo:
    type: string
    default: "202511"
  n_periodos:
    type: string
    default: "None"
  all_periodos:
    type: string
    default: "True"
  platinum_version:
    type: string
    default: "v1"
  feats_version:
    type: string
    default: "v1"
  target_version:
    type: string
    default: "v1"
  periodo:
    type: int
    default: 202511
  model_periodo:
    type: int
    default: 202511
  experiment_name:
    type: string
    default: "ml_pipeline_experiment"

outputs:

  output_datastore:
    type: uri_folder
    path: azureml://datastores/ml_data/paths/platinumdata
    mode: rw_mount
  output_feats_inicial_datastore:
    type: uri_folder
    path: azureml://datastores/ml_data/paths/features/inicial_regular
    mode: rw_mount
  output_target_inicial_datastore:
    type: uri_folder
    path: azureml://datastores/ml_data/paths/target/inicial_regular
    mode: rw_mount
  # output_predict_inicial_datastore:
  #   type: uri_folder
  #   path: azureml://datastores/ml_data/paths/predict/inicial_regular
  #   mode: rw_mount
  output_feats_continuidad_datastore:
    type: uri_folder
    path: azureml://datastores/ml_data/paths/features/continuidad_regular
    mode: rw_mount
  output_target_continuidad_datastore:
    type: uri_folder
    path: azureml://datastores/ml_data/paths/target/continuidad_regular
    mode: rw_mount

  output_feats_continuidad_horario_datastore:
    type: uri_folder
    path: azureml://datastores/ml_data/paths/features/continuidad_regular_horario
    mode: rw_mount
  output_target_continuidad_horario_datastore:
    type: uri_folder
    path: azureml://datastores/ml_data/paths/target/continuidad_regular_horario
    mode: rw_mount

  output_model_inicial_version:
    type: uri_file
  output_model_continuidad_version:
    type: uri_file
  output_model_continuidad_horario_version:
    type: uri_file


jobs:
  # ETL Job
  etl_job:
    type: command
    component: file:./src/data/etl.yml
    inputs:
      input_datastore: ${{parent.inputs.input_datastore}}
      ult_periodo: ${{parent.inputs.ult_periodo}}
      n_periodos: ${{parent.inputs.n_periodos}}
      all_periodos: ${{parent.inputs.all_periodos}}
      platinum_version: ${{parent.inputs.platinum_version}}
    outputs:
      output_datastore: ${{parent.outputs.output_datastore}}
  
  # Feature Engineering Jobs (run in parallel after ETL)
  features_inicial_job:
    type: command
    component: file:./src/features/inicial_regular.yml
    inputs:
      input_datastore: ${{parent.jobs.etl_job.outputs.output_datastore}}
      ult_periodo: ${{parent.inputs.ult_periodo}}
      platinum_version: ${{parent.inputs.platinum_version}}
      feats_version: ${{parent.inputs.feats_version}}
      target_version: ${{parent.inputs.target_version}}
      periodo: ${{parent.inputs.periodo}}
    outputs:
      output_feats_inicial_datastore: ${{parent.outputs.output_feats_inicial_datastore}}
      output_target_inicial_datastore: ${{parent.outputs.output_target_inicial_datastore}}


  # Feature Engineering Jobs (run in parallel after ETL)
  features_continuidad_job:
    type: command
    component: file:./src/features/continuidad_regular.yml
    inputs:
      input_datastore: ${{parent.jobs.etl_job.outputs.output_datastore}}
      ult_periodo: ${{parent.inputs.ult_periodo}}
      platinum_version: ${{parent.inputs.platinum_version}}
      feats_version: ${{parent.inputs.feats_version}}
      target_version: ${{parent.inputs.target_version}}
      periodo: ${{parent.inputs.periodo}}
    outputs:
      output_feats_continuidad_datastore: ${{parent.outputs.output_feats_continuidad_datastore}}
      output_target_continuidad_datastore: ${{parent.outputs.output_target_continuidad_datastore}}

  # Feature Engineering Jobs (run in parallel after ETL)
  features_continuidad_horario_job:
    type: command
    component: file:./src/features/continuidad_regular_horario.yml
    inputs:
      input_datastore: ${{parent.jobs.etl_job.outputs.output_datastore}}
      ult_periodo: ${{parent.inputs.ult_periodo}}
      platinum_version: ${{parent.inputs.platinum_version}}
      feats_version: ${{parent.inputs.feats_version}}
      target_version: ${{parent.inputs.target_version}}
      periodo: ${{parent.inputs.periodo}}
    outputs:
      output_feats_continuidad_horario_datastore: ${{parent.outputs.output_feats_continuidad_horario_datastore}}
      output_target_continuidad_horario_datastore: ${{parent.outputs.output_target_continuidad_horario_datastore}}


  # # Model train
  model_train_inicial_job:
    type: command
    component: file:./src/models/inicial_regular.yml
    inputs:
      input_feats_inicial_datastore: ${{parent.jobs.features_inicial_job.outputs.output_feats_inicial_datastore}}
      experiment_name: ${{parent.inputs.experiment_name}}
      feats_version: ${{parent.inputs.feats_version}}
      model_periodo: ${{parent.inputs.model_periodo}}

  model_train_continuidad_job:
    type: command
    component: file:./src/models/continuidad_regular.yml
    inputs:
      input_feats_continuidad_datastore: ${{parent.jobs.features_continuidad_job.outputs.output_feats_continuidad_datastore}}
      experiment_name: ${{parent.inputs.experiment_name}}
      feats_version: ${{parent.inputs.feats_version}}
      model_periodo: ${{parent.inputs.model_periodo}}

  model_train_continuidad_horario_job:
    type: command
    component: file:./src/models/continuidad_regular_horario.yml
    inputs:
      input_feats_continuidad_horario_datastore: ${{parent.jobs.features_continuidad_horario_job.outputs.output_feats_continuidad_horario_datastore}}
      experiment_name: ${{parent.inputs.experiment_name}}
      feats_version: ${{parent.inputs.feats_version}}
      model_periodo: ${{parent.inputs.model_periodo}}

  # Model Register Jobs
  register_inicial_job:
    type: command
    component: file:./src/register/inicial_regular.yml
    inputs:
      input_model_inicial_path: ${{parent.jobs.model_train_inicial_job.outputs.model_output_inicial}}
      model_periodo: ${{parent.inputs.model_periodo}}
    outputs:
      output_model_inicial_version: ${{parent.outputs.output_model_inicial_version}}

  register_continuidad_job:
    type: command
    component: file:./src/register/continuidad_regular.yml
    inputs:
      model_input_path: ${{parent.jobs.model_train_continuidad_job.outputs.model_output_continuidad}}
      model_periodo: ${{parent.inputs.model_periodo}}
    outputs:
      output_model_continuidad_version: ${{parent.outputs.output_model_continuidad_version}}

  register_continuidad_horario_job:
    type: command
    component: file:./src/register/continuidad_regular_horario.yml
    inputs:
      model_input_path: ${{parent.jobs.model_train_continuidad_horario_job.outputs.model_output_continuidad_horario}}
      model_periodo: ${{parent.inputs.model_periodo}}
    outputs:
      output_model_continuidad_horario_version: ${{parent.outputs.output_model_continuidad_horario_version}}


  # # Model predict
  # model_predict_job:
  #   type: command
  #   component: file:./src/predict/inicial_regular_v2.yml
  #   inputs:
  #     input_model_inicial_path: ${{parent.jobs.model_train_job.outputs.model_output}}
  #     input_feats_inicial_datastore: ${{parent.jobs.features_job.outputs.output_feats_inicial_datastore}}
  #     input_target_inicial_datastore: ${{parent.jobs.features_job.outputs.output_target_inicial_datastore}}
  #     experiment_name: ml_pipeline_experiment
  #     feats_version: "v1"
  #     target_version: "v1"
  #     periodo: 202511
  #     model_periodo: 202511
  #     model_version: "v1"
  #   outputs:
  #     output_predict_inicial_datastore: ${{parent.outputs.output_predict_inicial_datastore}}