# src/pipelines/diabetes_pipeline.yml
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: ml_pipeline
experiment_name: ml_experiment

settings:
  default_compute: azureml:ci        # Ajusta al nombre de tu compute
  default_datastore: azureml:workspaceblobstore

inputs:
  input_data:
    type: uri_file
    # Se asume que el archivo está dentro del repo en data/diabetes.csv.
    # Al crear el job, la CLI sube automáticamente este fichero al datastore.
    # https://aka.ms/ml-cli-v2-data-inputs
    path: ../../data/diabetes.csv

outputs:
  model_output: {}
  eval_output: {}

jobs:
  prep_job:
    type: command
    # component: file:../components/prep/prep.yml
    component: file:./src/data/prep.yml
    inputs:
      input_data: ${{parent.inputs.input_data}}
    outputs:
      train_data: {}
      test_data: {}
