name: Run Pipeline Base (Replica)

on:
  workflow_dispatch:
    inputs:
      ult_periodo:
        description: 'Último período (ej: 202511)'
        required: false
        default: '202511'
      n_periodos:
        description: 'Número de períodos'
        required: false
        default: 'None'
      all_periodos:
        description: 'Todos los períodos (True/False)'
        required: false
        default: 'True'
      platinum_version:
        description: 'Versión de platinum data'
        required: false
        default: 'v1'
  push:
    branches:
      - prod

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-ai-ml azure-identity
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Pipeline Script
      env:
        AZURE_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
        AZURE_RESOURCE_GROUP: ${{ fromJson(secrets.AZURE_CREDENTIALS).resourceGroup }}
        AZURE_WORKSPACE_NAME: ${{ fromJson(secrets.AZURE_CREDENTIALS).workspaceName }}
      run: |
          # Use workflow inputs if available, otherwise use defaults
          ULT_PERIODO="${{ github.event.inputs.ult_periodo || '202511' }}"
          N_PERIODOS="${{ github.event.inputs.n_periodos || 'None' }}"
          ALL_PERIODOS="${{ github.event.inputs.all_periodos || 'True' }}"
          PLATINUM_VERSION="${{ github.event.inputs.platinum_version || 'v1' }}"
          
          JOB_ID=$(az ml job create \
            --file pipeline_bas_v2.yml \
            --set jobs.etl_job.inputs.ult_periodo=$ULT_PERIODO \
            --set jobs.etl_job.inputs.n_periodos="$N_PERIODOS" \
            --set jobs.etl_job.inputs.all_periodos="$ALL_PERIODOS" \
            --set jobs.etl_job.inputs.platinum_version="$PLATINUM_VERSION" \
            --query name -o tsv)

          echo "Submitted job: $JOB_ID"
        

    # - name: Run Pipeline Script
      #   env:
    #     AZURE_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
    #     AZURE_RESOURCE_GROUP: ${{ fromJson(secrets.AZURE_CREDENTIALS).resourceGroup }}
    #     AZURE_WORKSPACE_NAME: ${{ fromJson(secrets.AZURE_CREDENTIALS).workspaceName }}
    #   run: |
    #     python pipeline_cloud_base_v2_actions.py
    #  opcional: exponerlo como output del step
         # echo "job_id=$JOB_ID" >> $GITHUB_OUTPUT